name: Pack Workflow
description: Pack application
inputs:
   configuration:
     required: true
     default: 'Release'
   solution_path:
     required: true
     default: ''
   additional_pack_properties:
     required: false
     default: ''
   artifacts_path:
     required: true
     default: ''
   token:
     required: true
     default: ''

runs:
  using: "composite"
      
  steps:

  - uses: actions/checkout@v2
  
  - name: Setup NuGet
    uses: NuGet/setup-nuget@v1.0.5

  - name: Add GitHub Source
    shell: pwsh
    run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/malonejv/index.json -Username malonejv -Password ${{ inputs.token }}
   
  - name: Nuget Restore Core Packages
    shell: pwsh
    run:  nuget restore ${{ inputs.solution_path }}
    
  - name: Download artifacts
    uses: actions/download-artifact@v2
    with:
        name: built-artifacts
        path: "built-artifacts"

  - name: Prepare Packages
    shell: pwsh
    run: |
          $solutionDir="${{ github.workspace }}\${{ inputs.solution_path }}" | Split-Path
          $projects = .\Get-ProjectsInSolution.ps1 ${{ inputs.solution_path }} -Type NonTestProjects | Split-Path
          $projects | ForEach-Object { 
            $folderName = Split-Path $_ -Leaf
            Copy-Item "${{ github.workspace }}\built-artifacts\$folderName\bin" -Destination "$solutionDir\$folderName\" -Recurse -Container
            nuget pack $_ -Properties Configuration=${{ inputs.configuration }} ${{inputs.additional_pack_properties }} -OutputDirectory ${{ inputs.artifacts_path }} }
          
  - name: Upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name: nuget-packages
      path: "${{ github.workspace }}\\nuget-artifacts\\*"
      if-no-files-found: error
      retention-days: 10
          
  - name: List artifacts
    shell: pwsh
    run:  Get-ChildItem -File -Path .\nuget-artifacts
