name: Pack Workflow
description: Pack application
inputs:
   MALONECORE_ENVIRONMENT:
     required: true
     default: 'Development'
   MALONECORE_VERBOSE:
     required: true
     default: 'True'
   SOLUTION_PATH:
     required: true
     default: ''
   PKG_ARTIFACTS_DIR:
     required: true
     default: ''
   SCRIPTS_DIR:
     required: true
     default: ''
   BUILD_ARTIFACTS_NAME:
     required: true
     default: 'build-artifacts'
   PACK_ARTIFACTS_NAME:
     required: true
     default: 'pack-artifacts'
   NUGET_SOURCE:
     required: true
     default: ''
   NUGET_USERNAME:
     required: true
     default: ''
   NUGET_PASSWORD:
     required: true
     default: ''

runs:
  using: "composite"

  steps:

  - uses: actions/checkout@v2

  - name: Setup NuGet
    uses: NuGet/setup-nuget@v1.0.5

  - name: Add GitHub as Nuget Source
    shell: pwsh
    run: nuget sources add -name "github" -Source ${{ inputs.NUGET_SOURCE }} -Username ${{ inputs.NUGET_USERNAME }} -Password ${{ inputs.NUGET_PASSWORD }}

  - name: Restore Nuget Packages
    shell: pwsh
    run:  nuget restore ${{ inputs.SOLUTION_PATH }}

  - name: Download built artifacts
    uses: actions/download-artifact@v2
    with:
        name: "${{ inputs.BUILD_ARTIFACTS_NAME }}"
        path: "${{ inputs.BUILD_ARTIFACTS_NAME }}"

  - name: Prepare Packages
    shell: pwsh
    run: |
          $solutionDir="${{ inputs.SOLUTION_PATH }}" | Split-Path
          $scriptsDir="${{ inputs.SCRIPTS_DIR }}"
          $solutionPath="${{ inputs.SOLUTION_PATH }}"
          $buildArtifactPath="${{ github.workspace }}\${{ inputs.BUILD_ARTIFACTS_NAME }}\*"
          $OutputDir="${{ inputs.PKG_ARTIFACTS_DIR }}"
          Invoke-Expression "$scriptsDir\Post-BuildEvent.ps1 -SolutionPath `"$solutionPath`" -Environment `"${{ inputs.MALONECORE_ENVIRONMENT }}`" -BuildArtifactsPath `"$buildArtifactPath`" -OutputDir `"$OutputDir`" -ShouldPack:([bool]::parse(`"$true`")) -Verbose:([bool]::parse(`"${{ inputs.MALONECORE_VERBOSE }}`"))"

  - name: Upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name:  "${{ inputs.PACK_ARTIFACTS_NAME }}"
      path: "${{ github.workspace }}\\${{ inputs.PACK_ARTIFACTS_NAME }}\\*"
      if-no-files-found: error
      retention-days: 1