name: Pack Workflow
description: Pack application
inputs:
   configuration:
     required: true
     default: 'Debug'
   solution_path:
     required: true
     default: ''
   additional_pack_properties:
     required: false
     default: ''
   artifacts_path:
     required: true
     default: ''
   allow_push:
     required: false
     default: false
   token:
     required: true
     default: ''

runs:
  using: "composite"
      
  steps:

  - uses: actions/checkout@v2
  
  - name: Setup NuGet
    uses: NuGet/setup-nuget@v1.0.5

  - name: Add GitHub Source
    shell: pwsh
    run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/malonejv/index.json -Username malonejv -Password ${{ inputs.token }}
    
  - name: Build malone.Core
    shell: pwsh
    run: msbuild ${{ inputs.solution_path }} /t:"Clean;Build" /p:Configuration=${{ inputs.configuration }}
  
  - name: Prepare Packages
    shell: pwsh
    if: ${{ fromJSON(inputs.allow_push) }}
    run:
         |
          $projects = .\Get-ProjectsInSolution.ps1 ${{ inputs.solution_path }} -Type NonTestProjects
          $projects | foreach{ nuget pack $_ -Properties Configuration=${{ inputs.configuration }} -Version ${{ steps.version_number.outputs.version_number }} ${{inputs.additional_pack_properties }} -OutputDirectory ${{ inputs.artifacts_path }} }
          
  - name: Upload artifacts
    if: ${{ inputs.allow_push }}
    uses: actions/upload-artifact@v2
    with:
      name: nuget-packages
      path: "${{ github.workspace }}\\nuget-artifacts\\*"
      if-no-files-found: error
      retention-days: 1
          
  - name: List artifacts
    if: ${{ inputs.allow_push }}
    shell: pwsh
    run:  Get-ChildItem -File -Path .\nuget-artifacts