// <auto-generated />
namespace malone.Core.Sample.Middle.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Change2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005240038453_Change2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
