// <auto-generated />
namespace malone.Core.Sample.EF.SqlServer.Middle.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change7));
        
        string IMigrationMetadata.Id
        {
            get { return "202210300156146_Change7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
