//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Commons.Localization.Resources
{
	/// <summary>
	/// Defines the <see cref="Contents" />.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Contents
	{
		/// <summary>
		/// Defines the resourceMan.
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		/// <summary>
		/// Defines the resourceCulture.
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Initializes a new instance of the <see cref="Contents"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Contents()
		{
		}

		/// <summary>
		/// Gets the ResourceManager.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Commons.Localization.Resources.Contents", typeof(Contents).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		/// Gets or sets the Culture.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		/// Gets the Logging_SupportId.
		/// </summary>
		internal static string Logging_SupportId
		{
			get
			{
				return ResourceManager.GetString("Logging_SupportId", resourceCulture);
			}
		}
	}
}
