name: Set-Env
description: Defines shared environment variables

runs:
  using: "composite"
      
  steps:

  - uses: actions/checkout@v2
  
  - name: "Defining development variables: "
    if: github.base_ref=='development' && startsWith(github.head_ref, 'feature/')
    shell: pwsh
    run: |
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_ENVIRONMENT=Development" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_CONFIGURATION=Debug" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_VERBOSE=True" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_SHOULDPACK=False" -Encoding utf-8
        echo "MALONECORE_ENVIRONMENT=Development" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_CONFIGURATION=Debug" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_VERBOSE=True" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_SHOULDPACK=False" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

  - name: "Defining development variables: "
    if: github.ref_name=='development'
    shell: pwsh
    run: |
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_ENVIRONMENT=Development" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_CONFIGURATION=Debug" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_VERBOSE=True" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_SHOULDPACK=True" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_NUGET_SYMBOL_PATTERN=malone.Core*.snupkg" -Encoding utf-8
        echo "MALONECORE_ENVIRONMENT=Development" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_CONFIGURATION=Debug" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_VERBOSE=True" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_SHOULDPACK=False" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_NUGET_SYMBOL_PATTERN=malone.Core*.snupkg" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      
  - name: "Defining hotfix production variables: "
    if: github.base_ref=='master' && (startsWith(github.head_ref, 'release/')  || startsWith(github.head_ref, 'hotfix/'))
    shell: pwsh
    run: |
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_ENVIRONMENT=Production" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_CONFIGURATION=Release" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_VERBOSE=True" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_SHOULDPACK=False" -Encoding utf-8
        echo "MALONECORE_ENVIRONMENT=Production" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_CONFIGURATION=Release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_VERBOSE=True" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_SHOULDPACK=False" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          
  - name: "Defining production variables: "
    if: github.ref_name=='master'
    shell: pwsh
    run: |
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_ENVIRONMENT=Production" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_CONFIGURATION=Release" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_VERBOSE=False" -Encoding utf-8
        Add-Content "${{ github.workspace }}\\.venv" -Value "MALONECORE_SHOULDPACK=True" -Encoding utf-8
        echo "MALONECORE_ENVIRONMENT=Production" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_CONFIGURATION=Release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_VERBOSE=False" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "MALONECORE_SHOULDPACK=True" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        
  
  - name: Upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name: "venv"
      path: "${{ github.workspace }}\\.venv"
      if-no-files-found: error
      retention-days: 1


