name: Deploy Workflow
description: Deploy application

inputs:
   PACK_ARTIFACTS_NAME:
     required: true
     default: 'pack-artifacts'
   PACKAGE_PATTERN:
     required: true
     default: ''
   SYMBOL_PATTERN:
     required: false
     default: ''
   NUGET_SOURCE:
     required: true
     default: ''
   NUGET_USERNAME:
     required: true
     default: ''
   NUGET_PASSWORD:
     required: true
     default: ''
     
runs:
  using: "composite"

  steps: 
  
  - name: Add GitHub as Nuget Source
    shell: pwsh
    run: nuget sources add -name "github" -Source ${{ inputs.NUGET_SOURCE }} -Username ${{ inputs.NUGET_USERNAME }} -Password ${{ inputs.NUGET_PASSWORD }}
    
  - name: Download packed artifacts
    uses: actions/download-artifact@v2
    with:
        name: "${{ inputs.PACK_ARTIFACTS_NAME }}"
        path: "${{ inputs.PACK_ARTIFACTS_NAME }}"

  - name: "Push Nuget Packages"
    shell: pwsh
    run: |
          cd "${{ github.workspace }}\\${{ inputs.PACK_ARTIFACTS_NAME }}"
          nuget push "${{ inputs.PACKAGE_PATTERN }}" -SkipDuplicate -source "github"
          if("${{ inputs.SYMBOL_PATTERN }}"-ne""){ nuget push "${{ inputs.SYMBOL_PATTERN }}" -SkipDuplicate -source "github"}
