name: Deploy Workflow
description: Deploy application

inputs:
   MALONECORE_NUGET_PATTERN:
     required: true
     default: ''
   MALONECORE_NUGET_SYMBOL_PATTERN:
     required: false
     default: ''
   PKG_ARTIFACTS_DIR:
     required: false
     default: ''
   PACK_ARTIFACTS_NAME:
     required: true
     default: 'pack-artifacts'
   NUGET_SOURCE:
     required: true
     default: ''
   NUGET_USERNAME:
     required: true
     default: ''
   NUGET_PASSWORD:
     required: true
     default: ''
     
runs:
  using: "composite"

  steps: 
  
  - name: Download packed artifacts
    uses: actions/download-artifact@v2
    with:
        name: "${{ inputs.PACK_ARTIFACTS_NAME }}"
        path: "${{ inputs.PACK_ARTIFACTS_NAME }}"

  - name: "Push Nuget Packages"
    shell: pwsh
    run: |
          nuget sources add -name "github" -Source ${{ inputs.NUGET_SOURCE }} -Username ${{ inputs.NUGET_USERNAME }} -Password ${{ inputs.NUGET_PASSWORD }}
          nuget setApiKey ${{ inputs.NUGET_PASSWORD }} -Source ${{ inputs.NUGET_SOURCE }}
          cd "${{ inputs.PKG_ARTIFACTS_DIR }}"
          nuget push "${{ inputs.MALONECORE_NUGET_PATTERN }}" -SkipDuplicate -source "github"
          if("${{ inputs.MALONECORE_NUGET_SYMBOL_PATTERN }}"-ne""){ nuget push "${{ inputs.MALONECORE_NUGET_SYMBOL_PATTERN }}" -SkipDuplicate -source "github"}
