name: Deploy Workflow
description: Deploy application

inputs:
  artifacts_path:
    required: true
    type: string
    default: ''
  allow_push:
    required: true
    default: false
  token:
     required: true
     default: ''
  
runs:
  using: "composite"

  steps: 
  
  - name: Add GitHub Source
    shell: pwsh
    run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/malonejv/index.json -Username malonejv -Password ${{ inputs.token }}
    
  - name: Download artifacts
    if: ${{ inputs.allow_push }}
    uses: actions/download-artifact@v2
    with:
        name: nuget-packages
        path: "nuget-packages"

  - name: List artifacts
    shell: pwsh
    run:  Get-ChildItem -File -Path .\nuget-packages

  - name: "Pushing Nuget Packages"
    if: ${{ inputs.allow_push }}
    shell: pwsh
    run: |
          cd .\nuget-packages
          nuget push *-dev.nupkg -SkipDuplicate -source "github"
          nuget push *-dev.snupkg -SkipDuplicate -source "github"
