name: Deploy Workflow
description: Deploy application

inputs:
  artifacs_path:
    required: true
    type: string
    default: ''
  allow_push:
    required: true
    type: boolean
    default: false
  
runs:
  using: "composite"

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps: 

  - uses: actions/download-artifact@v2
    with:
        name: nuget-packages
        path: ${ inputs.artifacts_path }

  - run: | 
          nuget push *-dev.nupkg -SkipDuplicate -source "github"
          nuget push *-dev.snupkg -SkipDuplicate -source "github"
