// <auto-generated />
namespace malone.Core.Sample.EF.SqlServer.Middle.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change4));
        
        string IMigrationMetadata.Id
        {
            get { return "202009140425038_Change4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
