//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Resources
{
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions
    {
        /// <summary>
        /// Defines the resourceMan.
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture.
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Exceptions"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions()
        {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class...
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class...
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the E300
        /// Looks up a localized string similar to Se produjo un error al intentar obtener los datos solicitados....
        /// </summary>
        internal static string E300
        {
            get
            {
                return ResourceManager.GetString("E300", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E301
        /// Looks up a localized string similar to Se produjo un error al intentar guardar los datos solicitados....
        /// </summary>
        internal static string E301
        {
            get
            {
                return ResourceManager.GetString("E301", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E302
        /// Looks up a localized string similar to Se produjo un error al intentar eliminar el dato solicitado....
        /// </summary>
        internal static string E302
        {
            get
            {
                return ResourceManager.GetString("E302", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E303
        /// Looks up a localized string similar to Se produjo un error al intentar actualizar los datos solicitados....
        /// </summary>
        internal static string E303
        {
            get
            {
                return ResourceManager.GetString("E303", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E304
        /// Looks up a localized string similar to No se encontraron resultados para la consulta realizada....
        /// </summary>
        internal static string E304
        {
            get
            {
                return ResourceManager.GetString("E304", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E305
        /// Looks up a localized string similar to Nombre de usuario o contraseña invalido....
        /// </summary>
        internal static string E305
        {
            get
            {
                return ResourceManager.GetString("E305", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E306
        /// Looks up a localized string similar to Debes confirmar el email primero....
        /// </summary>
        internal static string E306
        {
            get
            {
                return ResourceManager.GetString("E306", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E307
        /// Looks up a localized string similar to Usuario no autorizado....
        /// </summary>
        internal static string E307
        {
            get
            {
                return ResourceManager.GetString("E307", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E400
        /// Looks up a localized string similar to Error al obtener una lista ordenada de tipo {0}....
        /// </summary>
        internal static string E400
        {
            get
            {
                return ResourceManager.GetString("E400", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E401
        /// Looks up a localized string similar to Error al obtener una entidad de tipo {0}....
        /// </summary>
        internal static string E401
        {
            get
            {
                return ResourceManager.GetString("E401", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E402
        /// Looks up a localized string similar to Error al insertar una entidad de tipo {0}....
        /// </summary>
        internal static string E402
        {
            get
            {
                return ResourceManager.GetString("E402", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E403
        /// Looks up a localized string similar to Error al eliminar una entidad de tipo {0}....
        /// </summary>
        internal static string E403
        {
            get
            {
                return ResourceManager.GetString("E403", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E404
        /// Looks up a localized string similar to Error al actualizar una entidad de tipo {0}....
        /// </summary>
        internal static string E404
        {
            get
            {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the E480
        /// Looks up a localized string similar to Se produjo un error en la llamada al servicio {0}....
        /// </summary>
        internal static string E480
        {
            get
            {
                return ResourceManager.GetString("E480", resourceCulture);
            }
        }
    }
}
