//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Resources
{
	/// <summary>
	/// Defines the <see cref="T: Exceptions" />.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Exceptions
	{
		/// <summary>
		/// Defines the resourceMan.
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		/// <summary>
		/// Defines the resourceCulture.
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Initializes a new instance of the <see cref="T: Exceptions"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Exceptions()
		{
		}

		/// <summary>
		/// Gets the ResourceManager.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Resources.Exceptions", typeof(Exceptions).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		/// Gets or sets the Culture.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		/// Gets the E300.
		/// </summary>
		internal static string E300
		{
			get
			{
				return ResourceManager.GetString("E300", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E301.
		/// </summary>
		internal static string E301
		{
			get
			{
				return ResourceManager.GetString("E301", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E302.
		/// </summary>
		internal static string E302
		{
			get
			{
				return ResourceManager.GetString("E302", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E303.
		/// </summary>
		internal static string E303
		{
			get
			{
				return ResourceManager.GetString("E303", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E304.
		/// </summary>
		internal static string E304
		{
			get
			{
				return ResourceManager.GetString("E304", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E305.
		/// </summary>
		internal static string E305
		{
			get
			{
				return ResourceManager.GetString("E305", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E306.
		/// </summary>
		internal static string E306
		{
			get
			{
				return ResourceManager.GetString("E306", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E307.
		/// </summary>
		internal static string E307
		{
			get
			{
				return ResourceManager.GetString("E307", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E400.
		/// </summary>
		internal static string E400
		{
			get
			{
				return ResourceManager.GetString("E400", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E401.
		/// </summary>
		internal static string E401
		{
			get
			{
				return ResourceManager.GetString("E401", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E402.
		/// </summary>
		internal static string E402
		{
			get
			{
				return ResourceManager.GetString("E402", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E403.
		/// </summary>
		internal static string E403
		{
			get
			{
				return ResourceManager.GetString("E403", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E404.
		/// </summary>
		internal static string E404
		{
			get
			{
				return ResourceManager.GetString("E404", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the E480.
		/// </summary>
		internal static string E480
		{
			get
			{
				return ResourceManager.GetString("E480", resourceCulture);
			}
		}
	}
}
