//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Resources
{
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions
    {
                                private static global::System.Resources.ResourceManager resourceMan;

                                private static global::System.Globalization.CultureInfo resourceCulture;

                                [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions()
        {
        }

                                        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

                                                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

                                        internal static string E300
        {
            get
            {
                return ResourceManager.GetString("E300", resourceCulture);
            }
        }

                                        internal static string E301
        {
            get
            {
                return ResourceManager.GetString("E301", resourceCulture);
            }
        }

                                        internal static string E302
        {
            get
            {
                return ResourceManager.GetString("E302", resourceCulture);
            }
        }

                                        internal static string E303
        {
            get
            {
                return ResourceManager.GetString("E303", resourceCulture);
            }
        }

                                        internal static string E304
        {
            get
            {
                return ResourceManager.GetString("E304", resourceCulture);
            }
        }

                                        internal static string E305
        {
            get
            {
                return ResourceManager.GetString("E305", resourceCulture);
            }
        }

                                        internal static string E306
        {
            get
            {
                return ResourceManager.GetString("E306", resourceCulture);
            }
        }

                                        internal static string E307
        {
            get
            {
                return ResourceManager.GetString("E307", resourceCulture);
            }
        }

                                        internal static string E400
        {
            get
            {
                return ResourceManager.GetString("E400", resourceCulture);
            }
        }

                                        internal static string E401
        {
            get
            {
                return ResourceManager.GetString("E401", resourceCulture);
            }
        }

                                        internal static string E402
        {
            get
            {
                return ResourceManager.GetString("E402", resourceCulture);
            }
        }

                                        internal static string E403
        {
            get
            {
                return ResourceManager.GetString("E403", resourceCulture);
            }
        }

                                        internal static string E404
        {
            get
            {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }

                                        internal static string E480
        {
            get
            {
                return ResourceManager.GetString("E480", resourceCulture);
            }
        }
    }
}
