//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Commons.Exceptions.Resources
{
	/// <summary>
	/// Defines the <see cref="T: Exceptions" />.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Exceptions
	{
		/// <summary>
		/// Defines the resourceMan.
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		/// <summary>
		/// Defines the resourceCulture.
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Initializes a new instance of the <see cref="T: Exceptions"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Exceptions()
		{
		}

		/// <summary>
		/// Gets the ResourceManager.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Commons.Exceptions.Resources.Exceptions", typeof(Exceptions).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		/// Gets or sets the Culture.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		/// Gets the BUSINESS400.
		/// </summary>
		internal static string BUSINESS400
		{
			get
			{
				return ResourceManager.GetString("BUSINESS400", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS401.
		/// </summary>
		internal static string BUSINESS401
		{
			get
			{
				return ResourceManager.GetString("BUSINESS401", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS402.
		/// </summary>
		internal static string BUSINESS402
		{
			get
			{
				return ResourceManager.GetString("BUSINESS402", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS403.
		/// </summary>
		internal static string BUSINESS403
		{
			get
			{
				return ResourceManager.GetString("BUSINESS403", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS404.
		/// </summary>
		internal static string BUSINESS404
		{
			get
			{
				return ResourceManager.GetString("BUSINESS404", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS405.
		/// </summary>
		internal static string BUSINESS405
		{
			get
			{
				return ResourceManager.GetString("BUSINESS405", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSINESS406.
		/// </summary>
		internal static string BUSINESS406
		{
			get
			{
				return ResourceManager.GetString("BUSINESS406", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the BUSVAL500.
		/// </summary>
		internal static string BUSVAL500
		{
			get
			{
				return ResourceManager.GetString("BUSVAL500", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the CONF1.
		/// </summary>
		internal static string CONF1
		{
			get
			{
				return ResourceManager.GetString("CONF1", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the CONF2.
		/// </summary>
		internal static string CONF2
		{
			get
			{
				return ResourceManager.GetString("CONF2", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS600.
		/// </summary>
		internal static string DATAACCESS600
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS600", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS601.
		/// </summary>
		internal static string DATAACCESS601
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS601", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS602.
		/// </summary>
		internal static string DATAACCESS602
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS602", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS603.
		/// </summary>
		internal static string DATAACCESS603
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS603", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS604.
		/// </summary>
		internal static string DATAACCESS604
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS604", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the DATAACCESS605.
		/// </summary>
		internal static string DATAACCESS605
		{
			get
			{
				return ResourceManager.GetString("DATAACCESS605", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the SERVAG700.
		/// </summary>
		internal static string SERVAG700
		{
			get
			{
				return ResourceManager.GetString("SERVAG700", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the SERVICE300.
		/// </summary>
		internal static string SERVICE300
		{
			get
			{
				return ResourceManager.GetString("SERVICE300", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the TECH200.
		/// </summary>
		internal static string TECH200
		{
			get
			{
				return ResourceManager.GetString("TECH200", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the TECH201.
		/// </summary>
		internal static string TECH201
		{
			get
			{
				return ResourceManager.GetString("TECH201", resourceCulture);
			}
		}

		/// <summary>
		/// Gets the TECH202.
		/// </summary>
		internal static string TECH202
		{
			get
			{
				return ResourceManager.GetString("TECH202", resourceCulture);
			}
		}
	}
}
