//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Commons.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Commons.Exceptions.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar obtener los datos solicitados..
        /// </summary>
        internal static string BUSINESS400 {
            get {
                return ResourceManager.GetString("BUSINESS400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar guardar los datos solicitados..
        /// </summary>
        internal static string BUSINESS401 {
            get {
                return ResourceManager.GetString("BUSINESS401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar eliminar el dato solicitado..
        /// </summary>
        internal static string BUSINESS402 {
            get {
                return ResourceManager.GetString("BUSINESS402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar actualizar los datos solicitados..
        /// </summary>
        internal static string BUSINESS403 {
            get {
                return ResourceManager.GetString("BUSINESS403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron resultados para la consulta realizada..
        /// </summary>
        internal static string BUSINESS404 {
            get {
                return ResourceManager.GetString("BUSINESS404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña invalido..
        /// </summary>
        internal static string BUSINESS405 {
            get {
                return ResourceManager.GetString("BUSINESS405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes confirmar el email primero..
        /// </summary>
        internal static string BUSINESS406 {
            get {
                return ResourceManager.GetString("BUSINESS406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al tratar de obtener el nombre de seccion del tipo {0}.
        /// </summary>
        internal static string CONF1 {
            get {
                return ResourceManager.GetString("CONF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encuentra configurada la sección para el tipo {0}..
        /// </summary>
        internal static string CONF2 {
            get {
                return ResourceManager.GetString("CONF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener una lista ordenada de tipo {0}..
        /// </summary>
        internal static string DATAACCESS600 {
            get {
                return ResourceManager.GetString("DATAACCESS600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener una entidad de tipo {0}..
        /// </summary>
        internal static string DATAACCESS601 {
            get {
                return ResourceManager.GetString("DATAACCESS601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al insertar una entidad de tipo {0}..
        /// </summary>
        internal static string DATAACCESS602 {
            get {
                return ResourceManager.GetString("DATAACCESS602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar una entidad de tipo {0}..
        /// </summary>
        internal static string DATAACCESS603 {
            get {
                return ResourceManager.GetString("DATAACCESS603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar una entidad de tipo {0}..
        /// </summary>
        internal static string DATAACCESS604 {
            get {
                return ResourceManager.GetString("DATAACCESS604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la validación de CommandText {0}..
        /// </summary>
        internal static string DATAACCESS605 {
            get {
                return ResourceManager.GetString("DATAACCESS605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error en la llamada al servicio {0}..
        /// </summary>
        internal static string SERVAG700 {
            get {
                return ResourceManager.GetString("SERVAG700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado..
        /// </summary>
        internal static string SERVICE300 {
            get {
                return ResourceManager.GetString("SERVICE300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdón, algo salió mal.
        ///{0}: {1}.
        /// </summary>
        internal static string TECH200 {
            get {
                return ResourceManager.GetString("TECH200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error inesperado..
        /// </summary>
        internal static string TECH201 {
            get {
                return ResourceManager.GetString("TECH201", resourceCulture);
            }
        }
    }
}
