//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malone.Core.Commons.Exceptions.Resources
{
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions
    {
                                private static global::System.Resources.ResourceManager resourceMan;

                                private static global::System.Globalization.CultureInfo resourceCulture;

                                [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions()
        {
        }

                                        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("malone.Core.Commons.Exceptions.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

                                                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

                                        internal static string BUSINESS400
        {
            get
            {
                return ResourceManager.GetString("BUSINESS400", resourceCulture);
            }
        }

                                        internal static string BUSINESS401
        {
            get
            {
                return ResourceManager.GetString("BUSINESS401", resourceCulture);
            }
        }

                                        internal static string BUSINESS402
        {
            get
            {
                return ResourceManager.GetString("BUSINESS402", resourceCulture);
            }
        }

                                        internal static string BUSINESS403
        {
            get
            {
                return ResourceManager.GetString("BUSINESS403", resourceCulture);
            }
        }

                                        internal static string BUSINESS404
        {
            get
            {
                return ResourceManager.GetString("BUSINESS404", resourceCulture);
            }
        }

                                        internal static string BUSINESS405
        {
            get
            {
                return ResourceManager.GetString("BUSINESS405", resourceCulture);
            }
        }

                                        internal static string BUSINESS406
        {
            get
            {
                return ResourceManager.GetString("BUSINESS406", resourceCulture);
            }
        }

                                        internal static string BUSVAL500
        {
            get
            {
                return ResourceManager.GetString("BUSVAL500", resourceCulture);
            }
        }

                                        internal static string CONF1
        {
            get
            {
                return ResourceManager.GetString("CONF1", resourceCulture);
            }
        }

                                        internal static string CONF2
        {
            get
            {
                return ResourceManager.GetString("CONF2", resourceCulture);
            }
        }

                                        internal static string DATAACCESS600
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS600", resourceCulture);
            }
        }

                                        internal static string DATAACCESS601
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS601", resourceCulture);
            }
        }

                                        internal static string DATAACCESS602
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS602", resourceCulture);
            }
        }

                                        internal static string DATAACCESS603
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS603", resourceCulture);
            }
        }

                                        internal static string DATAACCESS604
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS604", resourceCulture);
            }
        }

                                        internal static string DATAACCESS605
        {
            get
            {
                return ResourceManager.GetString("DATAACCESS605", resourceCulture);
            }
        }

                                        internal static string SERVAG700
        {
            get
            {
                return ResourceManager.GetString("SERVAG700", resourceCulture);
            }
        }

                                        internal static string SERVICE300
        {
            get
            {
                return ResourceManager.GetString("SERVICE300", resourceCulture);
            }
        }

                                                internal static string TECH200
        {
            get
            {
                return ResourceManager.GetString("TECH200", resourceCulture);
            }
        }

                                        internal static string TECH201
        {
            get
            {
                return ResourceManager.GetString("TECH201", resourceCulture);
            }
        }

                                        internal static string TECH202
        {
            get
            {
                return ResourceManager.GetString("TECH202", resourceCulture);
            }
        }
    }
}
