name: Build Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      configuration:
        required: true
        type: string
        default: 'Debug'
      soluntion_path:
        required: true
        type: string
      artifacts_path:
        required: true
        type: string

env:
  ALLOW_PUSH_PACKAGES: "${{ github.event_name == 'push' && github.ref == 'refs/heads/${{ inputs.branch }}' }}"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      name: Build

      # The type of runner that the job will run on
      runs-on: windows-latest
      
     # Steps represent a sequence of tasks that will be executed as part of the job
      steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Add GitHub Source
        run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/malonejv/index.json -Username malonejv -Password ${{ secrets.GITHUB_TOKEN }}
          
      - name: Nuget Restore Core Packages
        run:  nuget restore ${{ inputs.soluntion_path }}
        
      - name: Build malone.Core
        run: msbuild ${{ inputs.soluntion_path }} /t:Build /p:Configuration=${{ inputs.configuration }}
            
      - name: Prepare Packages
        if: ${ env:ALLOW_PUSH_PACKAGES }
        run:
             |
              $projects = .\Get-ProjectsInSolution.ps1 ${{ inputs.soluntion_path }} -Type NonTestProjects
              $projects | foreach{ nuget pack $_ -Properties Configuration=${{ inputs.configuration }} -Suffix dev -IncludeReferencedProjects -Symbols -SymbolPackageFormat snupkg -OutputDirectory "${{ inputs.artifacts_path }}" }
              
      - name: Upload artifacts
        if: ${{ env:ALLOW_PUSH_PACKAGES }}
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: ${{ inputs.artifacts_path }}\*
          if-no-files-found: error
          retention-days: 1
          