# This is a basic workflow to help you get started with Actions

name: Integration to Development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - development
      - feature/**
      - master
      - release/**
      - hotfix/**
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - development
      - master
      - release/**
      - hotfix/**

env:
  ALLOW_PUSH_PACKAGES: "${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development')}}"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
      name: Setup
      # The type of runner that the job will run on
      runs-on: windows-latest

      outputs:
        Configuration: ${{ steps.set_configuration.configuration }}

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Setup
        run: echo Setup
        
      # Defines configuration
      - id: set_configuration
        name: Set configuration
        run: |
             $configuration = "Release"
             echo "CONFIGURATION=$configuration" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
             echo ::set-output name=Configuration::${env:CONFIGURATION}
             
  build:
      name: Build
      needs: setup

      # The type of runner that the job will run on
      runs-on: windows-latest
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build
        run: echo Build ${{ needs.setup.set_configuration.configuration }}

  nuget-pack:
      name: Preparing Nuget Packages
      needs: [setup,build]
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development')}}
      
      # The type of runner that the job will run on
      runs-on: windows-latest

      steps:
      
      # Defines configuration
      - name: Define Configuration
        run: |
             $configuration = "Release"
             echo "CONFIGURATION=$configuration" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
             
      - name: Pack
        run: echo Pack ${env:CONFIGURATION}

  deploy:
      name: Deploy
      needs: [setup,nuget-pack]
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development')}}
      
      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps: 
      
      - name: Push Packages
        run: echo Push ${env:CONFIGURATION}
        
      # Defines configuration
      - name: Define Configuration
        run: |
             $configuration = "Release"
             echo "CONFIGURATION=$configuration" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: "Pushing Nuget Packages"
        run: echo Build ${{ needs.setup.set_configuration.configuration }}
