
name: CI/CD to Development

on:
  push:
    branches:
      - development
      - feature/**
  pull_request:
    branches:
      - development

env:
  CONFIGURATION: "Debug"
  ALLOW_PUSH_PACKAGES: "${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}"
  VARIABLES_DIR: "src\\malone.Core\\bin\\Debug\\Variables"
  NUGET_ARTIFACTS_DIR: "${{ github.workspace }}\\nuget-artifacts"
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: development
      
      outputs:
        version_number: ${{ steps.version_number.outputs.version_number }}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        id: build_app
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              token: ${{ secrets.GITHUB_TOKEN }}
  
  pack:
      name: Pack
      runs-on: windows-latest
      environment: development
      needs: build
      
      steps:
      - uses: ./.github/actions/pack
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              additional_pack_properties: "-Version ${{ needs.build.outputs.version_number.MALONE_CORE_VER }}-dev${{ needs.build.outputs.version_number.MALONE_CORE_DEV_REV }} -IncludeReferencedProjects -Symbols -SymbolPackageFormat snupkg"
              artifacts_path: "${env:NUGET_ARTIFACTS_DIR}"
              allow_push: ${env:ALLOW_PUSH_PACKAGES}
              token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: development
      needs: pack

      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        with:
              artifacts_path: "${env:NUGET_ARTIFACTS_DIR}"
              allow_push: ${env:ALLOW_PUSH_PACKAGES}
              token: ${{ secrets.GITHUB_TOKEN }}
