# This is a basic workflow to help you get started with Actions

name: Integration to Development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - development
      - feature/**
      - master
      - release/**
      - hotfix/**
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - development
      - master
      - release/**
      - hotfix/**


env:
    ALLOW_PUSH_PACKAGES: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/development')}}
    CONFIGURATION: Debug
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
      name: 'Setup'
      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Setup
        run: echo Setup
      # Defines configuration
      - name: Define Configuration
        if: ${{ github.ref == 'refs/heads/master'}}
        run: |
             $configuration = "Release"
             echo "CONFIGURATION=$configuration" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

  build:
      name: 'Build'
      needs: setup

      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build
        run: echo Build ${env:CONFIGURATION}

  nuget-pack:
      name: "Preparing Nuget Packages"
      needs: build
      if: ${env:ALLOW_PUSH_PACKAGES}
      
      # The type of runner that the job will run on
      runs-on: windows-latest

      steps:
      - name: Pack
        run: echo Pack ${env:CONFIGURATION}

  deploy:
      name: "Pushing Nuget Packages"
      needs: nuget-pack
      if: ${env:ALLOW_PUSH_PACKAGES}
      
      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps: 
      - name: Push Packages
        run: echo Push ${env:CONFIGURATION}
        
