
name: CI/CD to Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  CONFIGURATION: "Debug"
  SOLUTION_PATH: "${{ github.workspace }}\\src\\malone.Core.sln"
  SCRIPTS_DIR: "${{ github.workspace }}\\src\\BuildScripts"
  MALONECORE_PKGOUTDIR: "${{ github.workspace }}\\pack-artifacts"
  MALONECORE_VERBOSE: ${{ secrets.MALONECORE_VERBOSE }}
  MALONECORE_ENVIRONMENT: ${{ secrets.MALONECORE_ENVIRONMENT}}
  SHOULD_COMMIT: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
  BRANCH: ${{ github.ref_name }}
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: development
      
      outputs:
        version_number: ${{steps.build_app.outputs.version_number}}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        id: build_app
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              scripts_dir: "${env:SCRIPTS_DIR}"
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              build_artifact_name: "build-artifacts"
              MALONECORE_VERBOSE: "${env:MALONECORE_VERBOSE}"
              MALONECORE_ENVIRONMENT: "${env:MALONECORE_ENVIRONMENT}"
              SHOULD_COMMIT: "${env:SHOULD_COMMIT}"
              BRANCH: "${env:BRANCH}"

  pack:
      name: Pack
      runs-on: windows-latest
      environment: development
      needs: build
      
      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pack
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              scripts_dir: "${env:SCRIPTS_DIR}"
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              MALONECORE_VERBOSE: "${env:MALONECORE_VERBOSE}"
              MALONECORE_ENVIRONMENT: "${env:MALONECORE_ENVIRONMENT}"
              MALONECORE_PKGOUTDIR: "${env:MALONECORE_PKGOUTDIR}"
              build_artifact_name: "build-artifacts"
              pack_artifact_name: "pack-artifacts"

  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: development
      needs: pack

      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              pack_artifact_name: "pack-artifacts"
              package_pattern: "*-dev*.nupkg"
              #symbol_pattern: "*-dev.snupkg"
