
name: CI/CD to Development

on:
  push:
    branches:
      - development
      - feature/**
  pull_request:
    branches:
      - development

env:
  CONFIGURATION: "Debug"
  VARIABLES_DIR: "src\\malone.Core\\bin\\Debug\\Variables"
  NUGET_ARTIFACTS_DIR: "${{ github.workspace }}\\nuget-artifacts"
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: development
      
      outputs:
        version_number: ${{ steps.build_app.outputs.version_number }}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        id: build_app
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              variables_dir: "${env:VARIABLES_DIR}"
              token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Output
        run: |
              echo "${{steps.build_app.outputs.version_number}}"
              echo ${{steps.build_app.outputs.version_number}}.MALONE_CORE_VER
              echo ${{steps.build_app.outputs.version_number}}.MALONE_CORE_DEV_REV
  
  pack:
      name: Pack
      runs-on: windows-latest
      environment: development
      needs: build
      
      steps:
      - name: Build Output
        run: echo "${{needs.build.outputs.version_number}}"
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pack
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              additional_pack_properties: "-Version ${{ needs.build.outputs.version_number }}.MALONE_CORE_VER-dev${{ needs.build.outputs.version_number }}.MALONE_CORE_DEV_REV -IncludeReferencedProjects -Symbols -SymbolPackageFormat snupkg"
              artifacts_path: "${env:NUGET_ARTIFACTS_DIR}"
              token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: development
      needs: pack

      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              artifacts_path: "${env:NUGET_ARTIFACTS_DIR}"
              token: ${{ secrets.GITHUB_TOKEN }}
