
name: CI/CD to Development

on:
  push:
    branches:
      - development
      - feature/**
  pull_request:
    branches:
      - development

env:
  CONFIGURATION: "Debug"
  SOLUTION_PATH: "${{ github.workspace }}\\src\\malone.Core.sln"
  VARIABLES_PATH: "${{ github.workspace }}\\src\\malone.Core\\bin\\Debug\\Variables"
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: development
      
      outputs:
        version_number: ${{steps.build_app.outputs.version_number}}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        id: build_app
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              variables_path: "${env:VARIABLES_PATH}"
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              build_artifact_name: "build-artifacts"

  pack:
      name: Pack
      runs-on: windows-latest
      environment: development
      needs: build
      
      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pack
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              additional_pack_properties: '-Version ("${{needs.build.outputs.version_number}}" | ConvertFrom-Json).MALONE_CORE_VER -Suffix ("dev" + ("${{needs.build.outputs.version_number}}" | ConvertFrom-Json).MALONE_CORE_DEV_REV) -IncludeReferencedProjects'
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              build_artifact_name: "build-artifacts"
              pack_artifact_name: "pack-artifacts"

  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: development
      needs: pack

      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              pack_artifact_name: "pack-artifacts"
              package_pattern: "*-dev*.nupkg"
              #symbol_pattern: "*-dev.snupkg"
