# This is a basic workflow to help you get started with Actions

name: Feature | PR to Development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - feature/**
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - development
      - release/**
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Add GitHub Source
        run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/malonejv/index.json -Username malonejv -Password ${{ secrets.GITHUB_TOKEN }}
    
      - name: Nuget Restore Core Packages
        run:  nuget restore src/malone.Core.sln
        
      - name: Build malone.Core
        run:  msbuild src/malone.Core.sln /t:Build /p:Configuration=Debug -verbosity:detailed
      
      - name: Get Data & Set Environment Variables
        shell: pwsh
        run: |
             $version = (Get-Content src/malone.Core/bin/Debug/Variables | Out-String |ConvertFrom-Json).MALONE_CORE_VER
             echo "MALONE_CORE_VER=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      
      - name: Echo Version Number
        run: echo "${env:MALONE_CORE_VER}"