# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - development
      - master
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
      # The type of runner that the job will run on
      runs-on: windows-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Nuget Restore Packages
        run:  nuget restore src/malone.Core.sln

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.GITHUB_TOKEN}}
               
      - name: Upload build number
        uses: actions/upload-artifact@v1
        with:
          name: BUILD_NUMBER
          path: BUILD_NUMBER
          
  job2:
      needs: job1
      runs-on: windows-latest
      steps:
      - name: Download build number
        uses: actions/download-artifact@v1
        with:
          name: BUILD_NUMBER
      - name: Restore build number
        id: buildnumber
        uses: einaregilsson/build-number@v2 
 
#    - name: Build the solution
#      run:  msbuild src/malone.Core.sln
