
name: CI/CD to Production

on:
  push:
    branches:
      - master
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - master
      - release/**
      - hotfix/**

env:
  CONFIGURATION: "Release"
  ALLOW_PUSH_PACKAGES: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
  VARIABLES_DIR: "src\\malone.Core\\bin\\Release\\Variables"
  NUGET_ARTIFACTS_DIR: "${{ github.workspace }}\\nuget-artifacts"
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: production
      
      outputs:
        version_number: ${{ steps.version_number.outputs.version_number }}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              token: ${{ secrets.GITHUB_TOKEN }}
           
   
  pack:
      name: Pack
      runs-on: windows-latest
      environment: development
      needs: build
      
      steps:
      - uses: ./.github/actions/pack
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: 'src\malone.Core.sln'
              artifacts_path: "${env:NUGET_ARTIFACTS_DIR}"
              allow_push: ${env:ALLOW_PUSH_PACKAGES}
              token: ${{ secrets.GITHUB_TOKEN }}
 
  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: development
      needs: pack
      
      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        with:
              artifacts_path: ${env:NUGET_ARTIFACTS_DIR}
              allow_push: ${env:ALLOW_PUSH_PACKAGES}
              token: ${{ secrets.GITHUB_TOKEN }}

  create-release:            
        name: Create Release
        runs-on: windows-latest
        environment: development

        steps:
            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              with:
                tag_name: v${{needs.build.outputs.version_number}}
                release_name: v${{needs.build.outputs.version_number}}
                draft: false
                prerelease: false