
name: CI/CD to Production

on:
  push:
    branches:
      - master
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - master
      - release/**
      - hotfix/**

env:
  CONFIGURATION: "Release"
  SOLUTION_PATH: "${{ github.workspace }}\\src\\malone.Core.sln"
  VARIABLES_PATH: "${{ github.workspace }}\\src\\malone.Core\\bin\\Release\\Variables"
  BUILD_ARTIFACT: "build-artifacts"
  PACK_ARTIFACT: "pack-artifacts"
  
jobs:
  build:
      name: Build
      runs-on: windows-latest
      environment: production
      
      outputs:
        version_number: ${{steps.build_app.outputs.version_number}}

      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build
        id: build_app
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              variables_path: "${env:VARIABLES_PATH}"
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              build_artifact_name: ${env:BUILD_ARTIFACT}
   
  pack:
      name: Pack
      runs-on: windows-latest
      environment: production
      needs: build
      
      steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/pack
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
              configuration: "${env:CONFIGURATION}"
              solution_path: "${env:SOLUTION_PATH}"
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              build_artifact_name: ${env:BUILD_ARTIFACT}
              pack_artifact_name: ${env:PACK_ARTIFACT}
 
  deploy:
      name: Deploy
      runs-on: windows-latest
      environment: production
      needs: pack
      
      steps: 
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
              nuget_source: "https://nuget.pkg.github.com/malonejv/index.json"
              nuget_username: "malonejv"
              nuget_password: "${{ secrets.GITHUB_TOKEN }}"
              pack_artifact_name: ${env:PACK_ARTIFACT}

  create-release:            
        name: Create Release
        runs-on: windows-latest
        environment: production

        steps:
            - name: Create Release
              if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
              with:
                tag_name: v("${{needs.build.outputs.version_number}}" | ConvertFrom-Json).MALONE_CORE_VER
                release_name: v("${{needs.build.outputs.version_number}}" | ConvertFrom-Json).MALONE_CORE_VER
                draft: false
                prerelease: false