
name: CI/CD

on:
  push:
    branches:
      - development
      - master
      - release/**
      - hotfix/**
  pull_request:
    branches:
      - development
      - master
      - release/**
      - hotfix/**

env:
  MALONECORE_ENVIRONMENT: ''
  MALONECORE_CONFIGURATION: ''
  MALONECORE_VERBOSE: ''
  MALONECORE_SHOULDPACK: ''
  MALONECORE_NUGET_PATTERN: 'malone.Core*.nupkg'
  MALONECORE_NUGET_SYMBOL_PATTERN: 'malone.Core*.snupkg'
  BRANCH: ${{ github.ref_name }}
  SHOULD_COMMIT: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master')  }}
  SOLUTION_PATH: "${{ github.workspace }}\\src\\malone.Core.sln"
  PKG_ARTIFACTS_DIR: "${{ github.workspace }}\\pack-artifacts"
  SCRIPTS_DIR: "${{ github.workspace }}\\src\\BuildScripts"
  GIT_USERNAME: "malonejv"
  GIT_USERMAIL: "malonejv@gmail.com"
  NUGET_SOURCE: "https://nuget.pkg.github.com/malonejv/index.json"
  NUGET_USERNAME: "malonejv"
  NUGET_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
      name: Build
      runs-on: windows-latest
      
      steps:

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/setenv
        id: set_env

      - name: "Echo Environmnet: "
        run: |
          Write-Host "MALONECORE_ENVIRONMENT: ${env:MALONECORE_ENVIRONMENT}"
          Write-Host "MALONECORE_CONFIGURATION: ${env:MALONECORE_CONFIGURATION}"
          Write-Host "MALONECORE_VERBOSE: ${env:MALONECORE_VERBOSE}"
          Write-Host "MALONECORE_SHOULDPACK: ${env:MALONECORE_SHOULDPACK}"
          Write-Host "MALONECORE_NUGET_PATTERN: ${env:MALONECORE_NUGET_PATTERN}"
          Write-Host "MALONECORE_NUGET_SYMBOL_PATTERN: ${env:MALONECORE_NUGET_SYMBOL_PATTERN}"
          Write-Host "BRANCH: ${env:BRANCH}"
          Write-Host "SHOULD_COMMIT: ${env:SHOULD_COMMIT}"

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/build
        id: build_app
        with:
              MALONECORE_ENVIRONMENT: "${env:MALONECORE_ENVIRONMENT}"
              MALONECORE_CONFIGURATION: "${env:MALONECORE_CONFIGURATION}"
              MALONECORE_VERBOSE: "${env:MALONECORE_VERBOSE}"
              MALONECORE_SHOULDPACK: "${env:MALONECORE_SHOULDPACK}"
              BRANCH: "${env:BRANCH}"
              SHOULD_COMMIT: "${env:SHOULD_COMMIT}"
              SOLUTION_PATH: "${env:SOLUTION_PATH}"
              PKG_ARTIFACTS_DIR: "${env:PKG_ARTIFACTS_DIR}"
              SCRIPTS_DIR: "${env:SCRIPTS_DIR}"
              BUILD_ARTIFACTS_NAME: "build-artifacts"
              GIT_USERNAME: "${env:GIT_USERNAME}"
              GIT_USERMAIL: "${env:GIT_USERMAIL}"
              NUGET_SOURCE: "${env:NUGET_SOURCE}"
              NUGET_USERNAME: "${env:NUGET_USERNAME}"
              NUGET_PASSWORD: "${env:NUGET_PASSWORD}"

  pack:
      name: Pack
      runs-on: windows-latest
      needs: build

      steps:

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/getenv
        id: get_env

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/pack
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master') }}
        with:
              MALONECORE_ENVIRONMENT: "${env:MALONECORE_ENVIRONMENT}"
              MALONECORE_VERBOSE: "${env:MALONECORE_VERBOSE}"
              SOLUTION_PATH: "${env:SOLUTION_PATH}"
              PKG_ARTIFACTS_DIR: "${env:PKG_ARTIFACTS_DIR}"
              SCRIPTS_DIR: "${env:SCRIPTS_DIR}"
              BUILD_ARTIFACTS_NAME: "build-artifacts"
              PACK_ARTIFACTS_NAME: "pack-artifacts"
              NUGET_SOURCE: "${env:NUGET_SOURCE}"
              NUGET_USERNAME: "${env:NUGET_USERNAME}"
              NUGET_PASSWORD: "${env:NUGET_PASSWORD}"

  deploy:
      name: Deploy
      runs-on: windows-latest
      needs: pack

      steps:

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/getenv
        id: get_env

      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/deploy
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master') }}
        with:
              MALONECORE_ENVIRONMENT: "${env:MALONECORE_ENVIRONMENT}"
              MALONECORE_NUGET_PATTERN: "${env:MALONECORE_NUGET_PATTERN}"
              MALONECORE_NUGET_SYMBOL_PATTERN: "${env:MALONECORE_NUGET_SYMBOL_PATTERN}"
              PKG_ARTIFACTS_DIR: "${env:PKG_ARTIFACTS_DIR}"
              PACK_ARTIFACTS_NAME: "pack-artifacts"
              NUGET_SOURCE: "${env:NUGET_SOURCE}"
              NUGET_USERNAME: "${env:NUGET_USERNAME}"
              NUGET_PASSWORD: "${env:NUGET_PASSWORD}"

  create-release:
      name: Create Release
      runs-on: windows-latest
      needs: deploy
      
      steps:
      
      - uses: actions/checkout@v3.1.0
      - name: Reading Version Number
        shell: pwsh
        id: read_version_number
        run: |
              $version = Get-Content -Raw .\src\CurrentVersion.json | ConvertFrom-Json
              
              # Set the output named "dev_version"
              Write-Host "::set-output name=dev_version::$version.development"
              
              # Set the output named "prod_version"
              Write-Host "::set-output name=prod_version::$version.production"

      - name: Download packed artifacts
        uses: actions/download-artifact@v3
        with:
            name: "pack-artifacts"
            path: "pack-artifacts"

      - uses: actions/checkout@v3.1.0
      - name: Create Prerelease
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/development' }}
        with:
          tag: v${{ steps.read_version_number.outputs.dev_version }}
          name: v${{ steps.read_version_number.outputs.dev_version }}
          prerelease: true
          artifacts: "pack-artifacts"
          token: ${{ secrets.GITHUB_TOKEN }} 

      - uses: actions/checkout@v3.1.0
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          tag: v${{ steps.read_version_number.outputs.prod_version }}
          name: v${{ steps.read_version_number.outputs.prod_version }}
          artifacts: "pack-artifacts"
          token: ${{ secrets.GITHUB_TOKEN }} 